apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.backendName }}
spec:
  selector:
    app: {{ .Values.deployments.backendName }}
  ports:
    - port: {{ .Values.images.backend.port }}
      targetPort: backend-port
  type: NodePort