apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: narsss1234/learner-report-cs-frontend:latest
          ports:
            - containerPort: 3000
              name: frontend-port
          imagePullPolicy: Always