apiVersion: v1
kind: Service
metadata: 
  name: {{ .Values.services.frontendName }}
spec:
  selector:
    app: {{ .Values.deployments.frontendName }}
  ports:
    - port: {{ .Values.images.frontend.port }}
      targetPort: frontend-port
  type: LoadBalancer