apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.mongoName }}
spec:
  selector:
    app: {{ .Values.deployments.mongoName }}
  ports:
    - port: {{ .Values.images.mongodb.port }}
      targetPort: mongo-port
  type: ClusterIP